<?php
	$sections['resume'] = array(
		'title'            => 'Resume',
		'type'             => 'timeline',
		'headerBackground' => 'assets/img/01-resume.jpg',
		'icon'             => 'format_quote',
		'content'          => array(

			array(
				'title'       => 'Summer Intern',
				'icon'        => 'globe',
				'color'       => 'success',
				'date'        => 'June 2018 - August 2018',
				'description' => '<ul><li><b>High Performance Computing (HPC) Cluster Administration: </b> Focus on HPC and scientific/engineering computing, deep technical support for HPC users and applications, HPC application and system performance analysis, delivery and support of HPC software development environment tools.</li> <li><b>Help-desk Services:</b> Help-desk services for some BSU&#39;s simulation codes, and development, delivery and support for scientific data analysis capabilities.</li></ul>',
			),

			array(
				'title'       => 'Undergraduate Research Assistant',
				'icon'        => 'globe',
				'color'       => 'success',
				'date'        => 'June 2017 - August 2017',
				'description' => '<ul><li><b>Research: </b>Researched and wrote a white paper on the use of Big Data in water management. Presented findings at undergraduate summer research symposium.</li> <li><b>NSF proposal: </b>Participated in the development of a NSF proposal.</li></ul>',
			),

			array(
				'title'       => 'Undergraduate Research Assistant',
				'icon'        => 'globe',
				'color'       => 'success',
				'date'        => 'June 2016 - August 2016',
				'description' => '<ul><li><b>Research: </b>Help designed and collected data for usability studies on products that require users to interact with digital environments ranging from commercial interactive tutoring systems to mobile devices.</li></ul>',
			),
		),
		'footer' => '<div class="btn-group btn-group-justified" role="group"><a class="btn btn-danger btn-raised btn-lg" href="//shared.hadriencroubois.com/CrouboisHadrienEN.pdf" target="_blank">View my full resume</a></div>',
	);
?>
