<?php
	$sections['code'] = array(
		'title'            => 'Code',
		'type'             => 'blocks',
		'settings'         => array('class' => 'info', 'width' => 'col-sm-4'),
		'headerBackground' => 'assets/img/02-code.jpg',
		'icon'             => 'polymer',
		'content'          => array(
			array(
				'title'   => 'Singly and Doubly Linked List',
				'content' => '<p>Both linked list are node implementation of the IndexedUnsortedList interface with fully functional iterators. I created a test suite to ensure correct functionality of the linked lists and iterators.</p>
				              <ul>
				              	<li>Language: Java</li>
								<li>Singly Linked List Sources: <a href="https://github.com/Maxxquoi/CS221/tree/master/SinglyLinkedList" target="_blank" class="text-%class%">Singly Linked List</a></li>
								<li>Doubly Linked List Sources: <a href="https://github.com/Maxxquoi/CS221/tree/master/DoublyLinkedList" target="_blank" class="text-%class%">Doubly Linked List</a></li>
				              </ul>',
			),
			// array(
			// 	'title'   => 'postMSE',
			// 	'content' => '<p>postMSE is a bootstrap base webpage engine. It is the successor to MSE-JPS and is used to power my personal webpage. One of the feature of postMSE is the management of bibliographic references. As MSE-JSP and postMSE are very different, both are maintained in parallel.</p>
			// 	              <p>Status: released & maintained</p>
			// 	              <div class="progress"><div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
			// 	              <ul>
			// 	              	<li>Language: PHP/JavaScript/CSS with Twig, Boostrap, and phpfastcache</li>
			// 	              	<li>Licence: GPLv3</li>
			// 	              	<li>Sources: <a href="https://github.com/Amxx/postMSE" target="_blank" class="text-%class%">https://github.com/Amxx/postMSE</a></li>
			// 	              </ul>',
			// ),
			// array(
			// 	'title'   => 'MSE-JPS',
			// 	'content' => '<p>MSE-JPS is a new version of the MSE engine using server side data generation from SQL database. This will allow no-script users to have a backup JavaScript free page while helping update the website content.</p>
			// 	              <p>Status: released & maintained</p>
			// 	              <div class="progress"><div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
			// 	              <ul>
			// 	              	<li>Language: PHP/SQL/JavaScript/CSS</li>
			// 	              	<li>Licence: GPLv3</li>
			// 	              	<li>Sources: <a href="https://github.com/Amxx/MSE-JPS" target="_blank" class="text-%class%">https://github.com/Amxx/MSE-JPS</a></li>
			// 	              </ul>',
			// ),
		),
	);

?>