<?php
	$sections['contact'] = array(
		'title'            => 'Contact',
		'type'             => 'tabs',
		'settings'         => array('class' => 'danger'),
		'headerBackground' => 'assets/img/03-contact.jpg',
		'icon'             => 'forum',
		'content'          => array(
		
			array(
				'title'   => 'Phone',
				'icon'    => 'call',
				'content' => '
					<p><span class="label label-danger" style="display: inline-block; width: 100px;">Mobile</span> &#32 &#32 &#32 317-658-0731</p>'
			),

			array(
				'title'   => 'Email',
				'icon'    => 'chat',
				'content' => '
					<p><span class="label label-danger" style="display: inline-block; width: 100px;">Personal</span><span style="display: inline-block; width: 200px;">massaquoi787@gmail.com</span></p>'
			),
		),
	);
?>
